<?php
/**
 * @file
 * Main file of Image class module.
 */
use Drupal\Core\Render\Markup;


function custompar_preprocess_paragraph__contact_form(&$variables)
{
//    dsm($variables['elements']['#paragraph']->get('field_insert_form')->getValue()[0]['value']);
    if ($variables['elements']['#paragraph']->get('field_insert_form')->getValue()[0]['value'] != 0) {
        $form = \Drupal::formBuilder()->getForm('Drupal\custompar\Form\CustomContactForm');
        $variables['contact_form'] = $form;
    }

}



/**
 * Implements hook_mail().
 */
function custompar_mail( $key, &$message, $params) {
    $options = [
        'langcode' => $message['langcode'],
    ];
    switch ($key) {
        case 'important_event':
            $message['subject'] = t('Number of updated nodes: @num', ['@num' => $params['updated_nodes']], $options);
            $message['body'][] = Markup::create($params['message']);
            //$message['body'][] = $params['message'];
            break;
    }
}
